[package]
name = "algorithm_rust"
version = "0.0.1"
authors = ["yangzj"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
